#
# A role for granting the permissions deemed necessary for deploying to kubernetes
# TODO: apiGroups like he said?
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
 name: robot-deployer
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - containers
  - endpoints
  - services
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
# and so on for other sets of apiGroups, resources, and verbs