apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-it-rolebinding
  namespace: test
subjects:
- kind: User
  name: jenkins-gke@YOUR-PROJECT.iam.gserviceaccount.com
  namespace: default
roleRef:
  kind: ClusterRole
  name: robot-deployer
  apiGroup: rbac.authorization.k8s.io
