kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted-rolebinding
  namespace: default
subjects:
- kind: User
  name: ${SA_EMAIL}
  namespace: default
roleRef:
  kind: ClusterRole
  name: robot-deployer
  apiGroup: rbac.authorization.k8s.io
